### ISSUE TITLE
Trouble with jobs

### ISSUE THREAD

**Issue by alvarovinagre** [bvdputte/kirby-queue#3]
Hello,

I tried to follow the instructions although I got a bit confused on how to correctly set this up.

So basically I'm trying to set a cron that hits this url: mydomain.com/gcapc/push every hour, but I'm unsure on where I should write that code. Is it on the config.php file or do I need to create it on a separate folder under site/queues? (I'm using the Poor man's cron option by the way)

I Appreciate any help, thank you!

**Comment by bvdputte** [comment]
Thanks for your patience.

I usually create a `site/workers/` directory where I put the the workers. These are basically php files that bootstrap Kirby and to their thing mangling through the jobs. This worker is the file that should be run by cron.

[Here](https://github.com/bvdputte/kirby-queue/blob/master/worker.php) is an example, but you probably need to adjust the paths.
