### ISSUE TITLE
Problem with Kirby > 3.6.2 and PHP 8.1

### ISSUE THREAD

**Issue by thathoff** [bvdputte/kirby-queue#8]
The bvdputte\kirbyQueue\Job::get() method does not seem to be compatible with Kirby\Toolkit\Obj::get()

`Declaration of bvdputte\kirbyQueue\Job::get(string $key, $default = null) must be compatible with Kirby\Toolkit\Obj::get($property, $fallback = null)`

**Comment by squareclouds** [comment]
having the same problem. im using php 7.4.12 and kirby 3.7.5

**Comment by bvdputte** [comment]
Should be fixed now.
Thx for reporting 👍
